spring:
  application:
    name: auth-service

  datasource:
    url: jdbc:postgresql://auth-db:5432/authdb
    username: auth_user
    password: auth_pass
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

  flyway:
    enabled: true
    baseline-on-migrate: true
    locations: classpath:db/migration

server:
  port: 9094

application:
  config:
    patient-url: http://patient-service:9091
    doctor-url: http://doctor-service:9092

  security:
    jwt-secret: ${JWT_SECRET}
    jwt-expiration-ms: 86400000  # 24H
