spring:
  application:
    name: auth-service

  config:
    import: "optional:vault://"

  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/authdb}
    username: ${SPRING_DATASOURCE_USERNAME:auth_user}
    password: ${SPRING_DATASOURCE_PASSWORD:auth_pass}
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

  flyway:
    enabled: true
    baseline-on-migrate: true
    locations: classpath:db/migration

  cloud:
    vault:
      host: ${VAULT_HOST:localhost}
      port: 8200
      scheme: http
      authentication: TOKEN
      token: ${VAULT_ROOT_TOKEN}
      kv:
        enabled: true
        backend: secret
        default-context: episante
        profile-separator: '/'
        version: 1

server:
  port: 9094

application:
  config:
    # ðŸ‘ˆ Fallback to localhost if running outside Docker
    patient-url: ${APPLICATION_CONFIG_PATIENT-URL:http://localhost:9091}
    doctor-url: ${APPLICATION_CONFIG_DOCTOR-URL:http://localhost:9092}

  security:
    jwt-secret: ${jwt-secret}

logging:
  level:
    root: INFO
    org.springframework: INFO
    org.hibernate.SQL: DEBUG
