  services:

  # --- The Gateway ---
    gateway:
      image: nginx:alpine
      ports:
        - "8089:80"  # The ONLY port exposed to your machine!
      volumes:
        - ../../gateway/nginx.conf:/etc/nginx/nginx.conf:ro
      depends_on:
        - frontend
        - auth-service
        - doctor-service
        - patient-service
        - appointment-service
      networks:
        - episante_net

    # --- Frontend ---
    frontend:
      build: ../../frontend
      # We DO NOT expose ports here (no "3000:80").
      # Only the Gateway talks to the frontend container.
      networks:
        - episante_net

    # --- Kafka Message Broker (KRaft Mode) ---
    kafka:
      image: bitnami/kafka:3.6
      container_name: episante-kafka
      ports:
        - "9094:9094"
      environment:
        - KAFKA_ENABLE_KRAFT=yes
        - KAFKA_CFG_PROCESS_ROLES=broker,controller
        - KAFKA_CFG_CONTROLLER_LISTENER_NAMES=CONTROLLER
        - KAFKA_CFG_LISTENERS=PLAINTEXT://:9092,CONTROLLER://:9093,EXTERNAL://:9094
        - KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP=CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT,EXTERNAL:PLAINTEXT
        # 'kafka:9092' is for your Spring Boot containers. 'localhost:9094' is for your host machine.
        - KAFKA_CFG_ADVERTISED_LISTENERS=PLAINTEXT://kafka:9092,EXTERNAL://localhost:9094
        - KAFKA_CFG_NODE_ID=1
        - KAFKA_CFG_CONTROLLER_QUORUM_VOTERS=1@kafka:9093
        - ALLOW_PLAINTEXT_LISTENER=yes
      volumes:
        - kafka_data:/bitnami/kafka
      networks:
        - episante_net

    patient-db:
      image: postgres:16
      container_name: patient-db
      environment:
        POSTGRES_DB: patientdb
        POSTGRES_USER: patient_user
        POSTGRES_PASSWORD: patient_pass
      volumes:
        - patient_data:/var/lib/postgresql/data
      networks:
        - episante_net

      healthcheck:
        test: ["CMD-SHELL", "pg_isready -U patient_user"]
        interval: 5s
        timeout: 5s
        retries: 5

    patient-service:
      build:
        context: ../../     # root of the whole project
        dockerfile: patient-service/Dockerfile
      container_name: patient-service
      depends_on:
        patient-db:
          condition: service_healthy  # <--- Waits for "pg_isready" to return true
      ports:
        - "9091:9091"
      environment:
        SPRING_DATASOURCE_URL: jdbc:postgresql://patient-db:5432/patientdb
        SPRING_DATASOURCE_USERNAME: patient_user
        SPRING_DATASOURCE_PASSWORD: patient_pass
        SPRING_KAFKA_BOOTSTRAP_SERVERS: kafka:9092
      networks:
        - episante_net

    doctor-db:
      image: postgres:16
      container_name: doctor-db
      environment:
        POSTGRES_DB: doctordb
        POSTGRES_USER: doctor_user
        POSTGRES_PASSWORD: doctor_pass
      volumes:
        - doctor_data:/var/lib/postgresql/data
      networks:
        - episante_net
      healthcheck:
        test: ["CMD-SHELL", "pg_isready -U doctor_user"]
        interval: 5s
        timeout: 5s
        retries: 5

    doctor-service:
      build:
        context: ../../
        dockerfile: doctor-service/Dockerfile
      container_name: doctor-service
      depends_on:
        doctor-db:
          condition: service_healthy  # <--- Waits for "pg_isready" to return true
      ports:
        - "9092:9092"
      environment:
        SPRING_DATASOURCE_URL: jdbc:postgresql://doctor-db:5432/doctordb
        SPRING_DATASOURCE_USERNAME: doctor_user
        SPRING_DATASOURCE_PASSWORD: doctor_pass
        SPRING_KAFKA_BOOTSTRAP_SERVERS: kafka:9092

      networks:
        - episante_net

    appointment-db:
      image: postgres:16
      container_name: appointment-db
      environment:
        POSTGRES_DB: appointmentdb
        POSTGRES_USER: appointment_user
        POSTGRES_PASSWORD: appointment_pass
      volumes:
        - appointment_data:/var/lib/postgresql/data
      networks:
        - episante_net
      healthcheck:
        test: ["CMD-SHELL", "pg_isready -U appointment_user"]
        interval: 5s
        timeout: 5s
        retries: 5

    appointment-service:
      build:
        context: ../../
        dockerfile: appointment-service/Dockerfile
      container_name: appointment-service
      depends_on:
        appointment-db:
          condition: service_healthy
      ports:
        - "9093:9093"
      environment:
        SPRING_DATASOURCE_URL: jdbc:postgresql://appointment-db:5432/appointmentdb
        SPRING_DATASOURCE_USERNAME: appointment_user
        SPRING_DATASOURCE_PASSWORD: appointment_pass
        SPRING_KAFKA_BOOTSTRAP_SERVERS: kafka:9092
        SPRING_APPLICATION_JSON: |
          {
            "application": {
              "config": {
                "doctor-url": "http://doctor-service:9092",
                "patient-url": "http://patient-service:9091"
              }
            }
          }
      networks:
        - episante_net

    auth-db:
      image: postgres:16
      container_name: auth-db
      environment:
        POSTGRES_DB: authdb
        POSTGRES_USER: auth_user
        POSTGRES_PASSWORD: auth_pass
      volumes:
        - auth_data:/var/lib/postgresql/data
      networks:
        - episante_net
      healthcheck:
        test: ["CMD-SHELL", "pg_isready -U auth_user"]
        interval: 5s
        timeout: 5s
        retries: 5

    auth-service:
      build:
        context: ../../          # root of the whole monorepo
        dockerfile: auth-service/Dockerfile
      container_name: auth-service
      depends_on:
        auth-db:
          condition: service_healthy
      ports:
        - "9094:9094"
      environment:
        SPRING_DATASOURCE_URL: jdbc:postgresql://auth-db:5432/authdb
        SPRING_DATASOURCE_USERNAME: auth_user
        SPRING_DATASOURCE_PASSWORD: auth_pass
        SPRING_KAFKA_BOOTSTRAP_SERVERS: kafka:9092
        # Feign URLs
        APPLICATION_CONFIG_PATIENT-URL: http://patient-service:9091
        APPLICATION_CONFIG_DOCTOR-URL: http://doctor-service:9092

        # JWT Secret for shared module
        APPLICATION_SECURITY_JWT-SECRET: "V5P0gvAl/J4VzUiijelQv79BLiLtm1KIrDqx9aQF2Mw="

      networks:
        - episante_net




  volumes:
    patient_data:
    doctor_data:
    appointment_data:
    auth_data:
    kafka_data:  


  networks:
    episante_net:
      driver: bridge
