spring:
  application:
    name: doctor-service

  config:
    import: "optional:vault://"

  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/doctordb}
    username: ${SPRING_DATASOURCE_USERNAME:doctor_user}
    password: ${SPRING_DATASOURCE_PASSWORD:doctor_pass}
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: false
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect

  flyway:
    enabled: true
    baseline-on-migrate: true
    locations: classpath:db/migration

  cloud:
    vault:
      host: ${VAULT_HOST:localhost}
      port: 8200
      scheme: http
      authentication: TOKEN
      token: ${VAULT_ROOT_TOKEN}
      kv:
        enabled: true
        backend: secret
        default-context: episante
        profile-separator: '/'
        version: 1

server:
  port: 9092

application:
  security:
    jwt-secret: ${jwt-secret}

logging:
  level:
    root: INFO
    org.springframework: INFO
    org.hibernate.SQL: DEBUG


