spring:
  application:
    name: doctor-service

  datasource:
    url: jdbc:postgresql://doctor-db:5432/doctordb
    username: doctor_user
    password: doctor_pass
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: false
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect

  flyway:
    enabled: true
    baseline-on-migrate: true
    locations: classpath:db/migration

server:
  port: 9092

application:
  security:
    jwt-secret: "V5P0gvAl/J4VzUiijelQv79BLiLtm1KIrDqx9aQF2Mw="

logging:
  level:
    root: INFO
    org.springframework: INFO
    org.hibernate.SQL: DEBUG   # disable in prod
    org.hibernate.type.descriptor.sql: TRACE

