spring:
  application:
    name: patient-service

  datasource:
    url: jdbc:postgresql://patient-db:5432/patientdb
    username: patient_user
    password: patient_pass
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: false
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect

  flyway:
    enabled: true
    baseline-on-migrate: true
    locations: classpath:db/migration

server:
  port: 9091

logging:
  level:
    root: INFO
    org.springframework: INFO
    org.hibernate.SQL: DEBUG   # disable in prod
    org.hibernate.type.descriptor.sql: TRACE

---
# ----------------------------------------------------
# DEV PROFILE (used locally)
# ----------------------------------------------------
#spring:
#  config:
#    activate:
#      on-profile: dev
#
#spring:
#  datasource:
#    url: jdbc:postgresql://localhost:5432/patientdb
#    username: patient_user
#    password: patient_pass
#
#server:
#  port: 9091
#
#---
## ----------------------------------------------------
## PROD PROFILE (used in Docker + VM deployment)
## ----------------------------------------------------
#spring:
#  config:
#    activate:
#      on-profile: prod
#
#spring:
#  datasource:
#    url: jdbc:postgresql://patient-db:5432/patientdb
#    username: patient_user
#    password: patient_pass
#
#server:
#  port: 9091
